### ISSUE TITLE
SY-UI-003 - Issue rendering photos to the home page (showing empty until clicked on)

### ISSUE THREAD

**Issue by mag9073** [mag9073/COMP72070_Sec3_Group9_Winter_2024#15]
noted issue with images rendering to home page - shows empty until it is clicked on.
will investigate and correct.

<img width="1280" alt="Screenshot 2024-03-05 131605" src="https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/146022076/21e1dac2-fe5c-475f-b180-5b22a0aac550">
<img width="1280" alt="Screenshot 2024-03-05 125710" src="https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/146022076/7723fe1e-77a1-46b3-a7e3-6f95c6e7278e">

**Comment by hsihak** [comment]
**Purpose:** 
This issue has been resolved now by introducing background workers prior to logging in to the homepage. These background workers will cache the images so that it is ready prior to loading the home page. We also introduce multithread by using threadpool allowing user to simultaneously access the the application. Thus, this issue has been fixed and will be close :) 

**Code Fix:**
![image](https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/92398417/78def595-dd52-499f-975e-04c387e7d4a4)


**Results:**
![image](https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/92398417/72680dcd-4180-43e5-9b0a-acc3adf81cb5)
