### ISSUE TITLE
SY-LOG-001 issue with Line endings server logger

### ISSUE THREAD

**Issue by mag9073** [mag9073/COMP72070_Sec3_Group9_Winter_2024#26]
<img width="1280" alt="Screenshot 2024-03-07 185352" src="https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/146022076/58ad0f07-da88-4b2e-bdf4-bb008e86bac9">
issue noted with logger and line endings normalization.

**Comment by hsihak** [comment]
**Purpose:**
This issue seems to be fixed now. We believe that it happened because the configurations issue since we are sharing the project on different computer. Our solution was by setting the configuration settings to Windows version. We have also refactor the logger functions which seems to fix the issue. Please find the screenshots of the After results below or in the Test Log Screenshots. Thus, I am going to close the issue now :) 

**Configuration Settings:**
![image](https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/92398417/eb434784-c88a-4c2c-8b95-b20d9da3da7f)


**Log textfile:**
![image](https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/92398417/2ecc7efd-0eed-489c-8af0-19b41126f491)

**Logger functions:**
![image](https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/92398417/e8ae8168-5ce4-47d3-839a-8498e20a7eab)
