### ISSUE TITLE
SY-STM-001 - Automatic  bypass for any user to admin settings.

### ISSUE THREAD

**Issue by mag9073** [mag9073/COMP72070_Sec3_Group9_Winter_2024#28]
This is an integration test for the Client and Server looking at the Server State Machine, noted the login for the Admin is N/F currently and any user is allowed to bypass. 
<img width="1280" alt="Screenshot 2024-03-07 221051" src="https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/146022076/b6da2d90-f4e8-4c4a-ba79-a8270df990c3">
<img width="1280" alt="Screenshot 2024-03-07 221831" src="https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/146022076/870460f1-7424-4c16-bee9-cfc03d362e4f">

**Comment by hsihak** [comment]
**Purpose:** 
This issue has been resolved by introducing a separate login for the Admin instead of sharing the same between client and admin. Thus, i can conclude that this issue has been resolved :D 

**Code Fix:**
![image](https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/92398417/7090868b-3540-4f55-8f3d-7abac0f6711f)

**Results:** 
 
![image](https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/92398417/230c7fbe-fc8d-4561-9295-8255ad7d0c46)

![image](https://github.com/mag9073/COMP72070_Sec3_Group9_Winter_2024/assets/92398417/3e666dc2-2a89-45cc-a74d-253fc9e2f4f6)
